In [1]:
import pandas as pd
import numpy as np


In [3]:

scalar = np.array(42)
print(scalar)
# number of dimensions
scalar.ndim

42


0

In [4]:

vector = np.array([1, 2, 3])
print(vector)
# number of dimensions
vector.ndim

[1 2 3]


1

In [6]:

matriz = np.array([[1, 2,3], [4, 5, 6]])
print(matriz)
# number of dimensions
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [11]:

tensor = np.array([[1, 2,3], [4, 5, 6]])
print(tensor)
# number of dimensions
tensor.ndim

[[1 2 3]
 [4 5 6]]


2

# Agregar o eliminar dimensiones

In [22]:
vector = np.array([1, 2, 3], ndim = 10)
print(vector)
#vector.ndim

TypeError: array() got an unexpected keyword argument 'ndim'

In [18]:
# expand dimensions (rows level)
expand  = np.expand_dims(np.array([1, 2, 3]), axis = 0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [20]:
print(vector, vector.ndim)

# delete dimensions
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[1 2 3] 1
[1 2 3] 1
