In [1]:
import pandas as pd
import numpy as np

In [2]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
np.zeros(3)

np.zeros((10, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
# a matrix filled of 1's
np.ones((10, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
# a n x m matriz with random values
np.random.rand(4, 10)*10

array([[0.76997802, 6.34234178, 7.22388379, 6.17040357, 1.02906543,
        0.32468584, 6.680419  , 5.41133772, 2.41715329, 8.16295161],
       [2.36792131, 0.76218477, 7.50025438, 0.59290507, 9.38643692,
        6.23713508, 4.45640924, 5.53715387, 3.72920328, 5.0202916 ],
       [7.17556383, 3.59614207, 7.53138588, 7.59721553, 9.19863029,
        1.38335307, 8.68023099, 1.78431635, 6.90173216, 8.6667191 ],
       [1.27782408, 7.47541732, 0.0574467 , 0.95286549, 3.42734503,
        4.67433695, 3.0879303 , 7.9944172 , 8.99859451, 0.33222888]])

In [21]:
# random integer
np.random.randint(1, 15)

5

In [22]:
np.random.randint(1, 100, (10, 10))

array([[18, 26, 57, 78, 79, 33, 63, 90, 59, 79],
       [12, 75, 48, 68, 78, 40, 72, 87, 61, 57],
       [64, 83, 64,  4, 33, 61, 77, 49, 93, 53],
       [90, 32, 80, 55, 49, 49, 46, 40, 73, 84],
       [15, 70, 21,  2,  9, 94, 80, 43, 29, 23],
       [63,  8, 65, 71, 23, 59, 64, 19, 29,  4],
       [17, 57, 20, 46, 26, 48, 74, 84, 77, 86],
       [94,  4, 94, 47, 30,  4, 59, 70, 89, 15],
       [61, 56, 74, 85, 63, 47, 76,  2, 89, 30],
       [34, 94, 22, 67, 83, 13, 73, 71, 12, 10]])