In [2]:
import pandas as pd
import numpy as np

In [3]:

arr = np.random.randint(1, 10, (3, 2))

In [5]:
print(arr)

[[6 6]
 [2 1]
 [3 8]]


In [7]:
# change a 3x2 array to 1x6
arr.reshape(1, 6)

array([[6, 6, 2, 1, 3, 8]])

In [8]:
arr.reshape(2, 3)

array([[6, 6, 2],
       [1, 3, 8]])

In [13]:
arr

array([[6, 6],
       [2, 1],
       [3, 8]])

In [11]:
np.reshape(arr, (2, 3), 'C')

array([[6, 6, 2],
       [1, 3, 8]])

In [12]:
np.reshape(arr, (2, 3), 'F')

array([[6, 3, 1],
       [2, 6, 8]])

In [14]:
np.reshape(arr, (2, 3), 'A')

array([[6, 6, 2],
       [1, 3, 8]])