In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1, 20, 10)

In [4]:
matriz = arr.reshape(2, 5)
matriz

array([[ 2, 16,  1, 11, 15],
       [10, 14, 17, 17, 19]])

In [5]:
# biggest number of the array
arr.max()

19

In [7]:
# max value by column
matriz.max(0)


array([10, 16, 17, 17, 19])

In [10]:
matriz.argmax(0)

array([1, 0, 1, 1, 1], dtype=int64)

In [6]:
# max value of the matrix 
matriz.max()

19

In [11]:
matriz.min(0)

array([ 2, 14,  1, 11, 15])

In [12]:
arr.argmin()

2

In [13]:
matriz.argmin(1)

array([2, 0], dtype=int64)

In [17]:
# peak to peak (difference between min and max)
arr.ptp()

18

In [19]:
print(matriz)
matriz.ptp(0)

[[ 2 16  1 11 15]
 [10 14 17 17 19]]


array([ 8,  2, 16,  6,  4])

In [23]:
np.percentile(arr, 100)

19.0

In [24]:
arr.sort()
arr

array([ 1,  2, 10, 11, 14, 15, 16, 17, 17, 19])

In [25]:
np.median(arr)

14.5

In [26]:
np.median(matriz, 1)

array([10., 17.])

In [28]:
# standard deviation
np.std(arr)

# variance
np.var(arr)


35.36

In [29]:
np.mean(arr)

12.2

In [48]:
# concatenate
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
print(a)


[[1 2]
 [3 4]]


In [49]:
np.concatenate((a, b), axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [44]:
a.ndim
b.ndim

1

In [51]:
b =np.expand_dims(b, axis = 1)
print(b)

[[5]
 [6]]


In [52]:
np.concatenate((a, b.T), axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1