In [1]:
import numpy as np


In [3]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
slice_of_arr = arr[0:6]

In [7]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [8]:
slice_of_arr[:] = 0
slice_of_arr

array([0, 0, 0, 0, 0, 0])

In [9]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [15]:
arr_copy = arr.copy()
arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [16]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [17]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])