In [1]:
import numpy as np


In [3]:
arr = np.linspace(1, 10, 10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [4]:
arr > 5


array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [6]:
indices_cond = arr > 5

In [8]:
# values bigger than 5 and less than 9
arr[(indices_cond) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [9]:
arr[arr > 5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)