In [1]:
import numpy as np


In [2]:
lista = [1, 2]
list

list

In [3]:
lista * 2

[1, 2, 1, 2]

In [4]:
arr = np.arange(0, 10)
arr2 = arr.copy()

# Operations

In [5]:
arr *2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [9]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
matriz = arr.reshape(2, 5)
matriz2 = matriz.copy()

In [14]:
matriz + matriz2


array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [15]:
np.matmul(matriz, matriz.T)

array([[ 30,  80],
       [ 80, 255]])

In [16]:
matriz @matriz2.T

array([[ 30,  80],
       [ 80, 255]])